version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/examples/*"
      - "/templates/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fork-ts-checker-webpack-plugin"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    groups:
      dependencies:
        group-by: dependency-name
        patterns:
          - "*"
