<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>AspNet.Frontend.Templates</PackageId>
    <Title>ASP.NET Frontend Templates</Title>
    <Authors>Baune8D</Authors>
    <Description>dotnet new templates for ASP.NET Core MVC and Razor Pages with Vite or Webpack, in JavaScript or TypeScript. Per-view bundles, hot reload in development and hashed assets in production.</Description>
    <PackageTags>dotnet-new;templates;aspnetcore;mvc;razor-pages;vite;webpack;typescript;frontend</PackageTags>
    <PackageProjectUrl>https://github.com/Baune8D/AspNet.Frontend.Templates</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Baune8D/AspNet.Frontend.Templates</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReleaseNotes>https://github.com/Baune8D/AspNet.Frontend.Templates/releases</PackageReleaseNotes>
    <PackageType>Template</PackageType>
    <TargetFramework>net10.0</TargetFramework>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <LocalizeTemplates>false</LocalizeTemplates>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.TemplateEngine.Tasks" Version="*" PrivateAssets="all" IsImplicitlyDefined="true"/>
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="AspNet.Mvc.Vite\**\*" Exclude="**\bin\**;**\obj\**;**\node_modules\**;**\dist\**" />
    <Content Include="AspNet.Mvc.Vite.TypeScript\**\*" Exclude="**\bin\**;**\obj\**;**\node_modules\**;**\dist\**" />
    <Content Include="AspNet.Mvc.Webpack\**\*" Exclude="**\bin\**;**\obj\**;**\node_modules\**;**\dist\**" />
    <Content Include="AspNet.Mvc.Webpack.TypeScript\**\*" Exclude="**\bin\**;**\obj\**;**\node_modules\**;**\dist\**" />
    <Content Include="AspNet.RazorPages.Vite\**\*" Exclude="**\bin\**;**\obj\**;**\node_modules\**;**\dist\**" />
    <Content Include="AspNet.RazorPages.Vite.TypeScript\**\*" Exclude="**\bin\**;**\obj\**;**\node_modules\**;**\dist\**" />
    <Content Include="AspNet.RazorPages.Webpack\**\*" Exclude="**\bin\**;**\obj\**;**\node_modules\**;**\dist\**" />
    <Content Include="AspNet.RazorPages.Webpack.TypeScript\**\*" Exclude="**\bin\**;**\obj\**;**\node_modules\**;**\dist\**" />
    <Compile Remove="**\*" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
